[package]
name = "vatsimfsdpacket"
version = "0.1.0"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
text_io = "0.1.8"
pnet = "0.26.0"
ascii = "1.0.0"
requests = "0.0.30"